# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('contact_num', models.CharField(max_length=15)),
                ('street', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=15)),
            ],
        ),
    ]
